/home/runner/work/dashboard/dashboard/clones/cpython/Doc/glossary.rst:107: WARNING: inconsistent term references in translated message. original: [':term:`asynchronous iterator`', ':meth:`~object.__anext__`', ':keyword:`yield`'], translated: [':term:`асинхронний ітератор`', ':meth:`~object.__anext__`'] [i18n.inconsistent_references]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/howto/clinic.rst:: ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs. [docutils]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/tutorial/appendix.rst:13: WARNING: inconsistent term references in translated message. original: [':term:`REPL`'], translated: [] [i18n.inconsistent_references]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/tutorial/interactive.rst:19: WARNING: inconsistent term references in translated message. original: [':ref:`automatically enabled <rlcompleter-config>`', ':meth:`~object.__getattr__`'], translated: [':meth:`~object.__getattr__`'] [i18n.inconsistent_references]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/library/stdtypes.rst:184: WARNING: inconsistent term references in translated message. original: [':meth:`~object.__lt__`', ':meth:`~object.__le__`', ':meth:`~object.__gt__`', ':meth:`~object.__ge__`', ':meth:`~object.__lt__`', ':meth:`~object.__eq__`'], translated: [':meth:`~object.__lt__`', ':meth:`~object.__le__`', ':meth:`~object.__ge__`', ':meth:`~object.__lt__`', ':meth:`~object.__eq__`'] [i18n.inconsistent_references]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/library/stdtypes.rst:577: WARNING: inconsistent term references in translated message. original: [':data:`sys.byteorder`'], translated: [] [i18n.inconsistent_references]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/glossary.rst:12:<translated>:1: WARNING: term not in glossary: 'інтерактивної' [ref.term]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/glossary.rst:19:<translated>:1: WARNING: term not in glossary: 'інтерактивної' [ref.term]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/glossary.rst:1173:<translated>:1: WARNING: term not in glossary: 'інтерактивної' [ref.term]
/home/runner/work/dashboard/dashboard/clones/cpython/Doc/library/sqlite3.rst:38:<translated>:1: WARNING: undefined label: 'sqlite3-tutorial`вчить як використовувати :mod:' [ref.ref]

Theme error!

Versions
========

* Platform:         linux; (Linux-6.8.0-1021-azure-x86_64-with-glibc2.39)
* Python version:   3.13.2 (CPython)
* Sphinx version:   8.2.3
* Docutils version: 0.21.2
* Jinja2 version:   3.1.6
* Pygments version: 2.19.1

Last Messages
=============



    generating indices...
    genindex
    py-modindex
    done
    writing additional pages...
    download
    failed
    Writing glossary.json

Loaded Extensions
=================

* sphinx.ext.mathjax (8.2.3)
* alabaster (1.0.0)
* sphinxcontrib.applehelp (2.0.0)
* sphinxcontrib.devhelp (2.0.0)
* sphinxcontrib.htmlhelp (2.1.0)
* sphinxcontrib.serializinghtml (2.0.0)
* sphinxcontrib.qthelp (2.0.0)
* audit_events (1.0)
* availability (1.0)
* c_annotations (1.0)
* changes (1.0)
* glossary_search (1.0)
* implementation_detail (1.0)
* issue_role (1.0)
* lexers (1.0)
* misc_news (1.0)
* pydoc_topics (1.0)
* pyspecific (1.0)
* sphinx.ext.coverage (8.2.3)
* sphinx.ext.doctest (8.2.3)
* sphinx.ext.extlinks (8.2.3)
* python_docs_theme (2025.2)

Traceback
=========

    Traceback (most recent call last):
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/html/__init__.py", line 1212, in handle_page
        output = self.templates.render(templatename, ctx)
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/jinja2glue.py", line 217, in render
        return self.environment.get_template(template).render(context)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
        self.environment.handle_exception()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/home/runner/work/dashboard/dashboard/clones/cpython/Doc/tools/templates/download.html", line 12, in top-level template code
        {% set dl_version = release %}
        ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/dashboard/dashboard/clones/cpython/Doc/tools/templates/layout.html", line 1, in top-level template code
        {% extends "!layout.html" %}
        ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/python_docs_theme/layout.html", line 64, in top-level template code
        <option value="dark">{{ _('Dark') }}</option>
        ^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/themes/classic/layout.html", line 2, in top-level template code
        {%- extends "basic/layout.html" %}
        ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/themes/basic/layout.html", line 149, in top-level template code
        {%- block content %}
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/themes/basic/layout.html", line 153, in block 'content'
        {%- block document %}
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/themes/basic/layout.html", line 159, in block 'document'
        {% block body %} {% endblock %}
        ^^^^^^^^^^^^^
      File "/home/runner/work/dashboard/dashboard/clones/cpython/Doc/tools/templates/download.html", line 16, in block 'body'
        <h1>{% trans %}Download Python {{ dl_version }} Documentation{% endtrans %}</h1>
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: unsupported format character '?' (0x441) at index 27
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/cmd/build.py", line 432, in build_main
        app.build(args.force_all, args.filenames)
        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/application.py", line 426, in build
        self.builder.build_update()
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 375, in build_update
        self.build(
        ~~~~~~~~~~^
            to_build,
            ^^^^^^^^^
        ...<2 lines>...
            method='update',
            ^^^^^^^^^^^^^^^^
        )
        ^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 457, in build
        self.finish()
        ~~~~~~~~~~~^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/html/__init__.py", line 689, in finish
        self.finish_tasks.add_task(self.gen_additional_pages)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/util/parallel.py", line 46, in add_task
        res = task_func()  # type: ignore[call-arg]
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/util/display.py", line 97, in wrapper
        return f(*args, **kwargs)
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/html/__init__.py", line 716, in gen_additional_pages
        self.handle_page(pagename, {}, template)
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/_temp/setup-uv-cache/environments-v2/generate-metadata-12cc6f2609cc9eaf/lib/python3.13/site-packages/sphinx/builders/html/__init__.py", line 1228, in handle_page
        raise ThemeError(msg) from exc
    sphinx.errors.ThemeError: An error happened in rendering the page download.
    Reason: ValueError("unsupported format character '?' (0x441) at index 27")


The full traceback has been saved in:
/tmp/sphinx-err-y8k177zh.log

To report this error to the developers, please open an issue at <https://github.com/sphinx-doc/sphinx/issues/>. Thanks!
Please also report this if it was a user error, so that a better error message can be provided next time.
